// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms. 

var first = 0;
var second = 1;
var max = 4000000;
var sum = 0;
var evenSum = 0;

while(sum < max)
{
    
 sum = first + second;
   
   if(sum % 2 === 0) 
   {
       evenSum = evenSum + sum;
   }
    
 first = second;
 second = sum;
    
}


console.log(evenSum); //logs 4613732

